server:
  port: 8082
  servlet:
    context-path: /LeaveWord
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.130:3306/leaveword?characterEncoding=utf8&useSSL=false
    username: root
    password: MyNewPass4!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
